### ISSUE TITLE
HTTP 500 Error on [[!AdvSearchForm]]

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [Coroico/AdvSearch#77]
Hello! 
When I add [[!AdvSearchForm]] I get a 500 error (blank page).
What could be the reason? (error log is empty).
Please help. Thanks.

Versions:
MODX 2.3/2.3.2
AdvSearch 1.0.1-pl
ZendFramework-1.12.9-minimal

**Comment by 0x4E69676874466F78** [comment]
https://github.com/modxcms/revolution/issues/11749
I applied this change and the error is gone.

**Comment by alkrauss48** [comment]
The fix that your link discussed was merged into AdvSearch in pull request #73 during September 2014, before this issue was even opened. I ran into this same problem again today too.

There are no updates in ModX for AdvSearch, so I know I'm running the most recent version (1.0.1-pl). Was a new version of this plugin, which would have included that fix, forgotten to be published to ModX?

**Comment by goldsky** [comment]
I'll post an update soon

**Comment by alkrauss48** [comment]
:+1:

**Comment by matdave** [comment]
Bump

**Comment by goldsky** [comment]
download 2.0.0-beta1
